export const GET_SERVICES = 'GET_SERVICES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS'
export const CLEAR_SERVICE_DETAILS = 'CLEAR_SERVICE_DETAILS'
export const UPDATE_SERVICE_DETAILS = 'UPDATE_SERVICE_DETAILS'

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';

export const GET_TEMPLATE_DETAILS = 'GET_TEMPLATES_DETAILS';
export const UPDATE_TEMPLATE_DETAILS = 'UPDATE_TEMPLATES_DETAILS';
export const CLEAR_TEMPLATE_DETAILS = 'CLEAR_TEMPLATE_DETAILS';

export const GET_REQUIREMENTS = 'GET_REQUIREMENTS';

export const GET_REVIEWS = 'GET_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

export const GET_REVIEW_DETAILS = 'GET_REVIEW_DETAILS';
export const CLEAR_REVIEW_DETAILS = 'CLEAR_REVIEW_DETAILS';
export const COMPLETE_REVIEW = 'COMPLETE_REVIEW';

export const GET_TEST_CASE = 'GET_TEST_CASE';
export const CLEAR_TEST_CASES = 'CLEAR_TEST_CASES';
export const UPDATE_TEST_CASE = 'UPDATE_TEST_CASE';
export const BULK_UPDATE_TEST_CASE = 'BULK_UPDATE_TEST_CASE';

export const GET_FINDINGS = 'GET_FINDINGS';
export const CREATE_FINDING = 'CREATE_FINDING';
export const UPDATE_FINDING = 'UPDATE_FINDING';
export const CLEAR_FINDINGS = 'CLEAR_FINDINGS';
export const DELETE_FINDING = 'DELETE_FINDING';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOAD = 'USER_LOAD';
export const USER_LOADING = 'USER_LOADING';

export const JIRA_GET_TRANSITIONS = 'JIRA_GET_TRANSITIONS';
export const JIRA_DELETE_TRANSITION = 'JIRA_DELETE_TRANSITION';
export const JIRA_UPDATE_TRANSITION = 'JIRA_UPDATE_TRANSITION';
export const JIRA_UPDATING_TRANSITION = 'JIRA_UPDATING_TRANSITION';
export const JIRA_UPDATE_TRANSITION_ERROR = 'JIRA_UPDATE_TRANSITION_ERROR';
export const JIRA_CREATE_TRANSITION = 'JIRA_CREATE_TRANSITION';
export const JIRA_CREATE_TRANSITION_ERROR = 'JIRA_CREATE_TRANSITION_ERROR';
export const JIRA_CREATING_TRANSITION = 'JIRA_CREATING_TRANSITION';
export const JIRA_GET_GARRETT_ACTIONS = 'JIRA_GET_GARRETT_ACTIONS';
export const JIRA_GET_ISSUES = 'JIRA_GET_ISSUES';
export const JIRA_GET_STATUSES = 'JIRA_GET_STATUSES';

export const CREATE_SECURITY_TEST = 'CREATE_SECURITY_TEST';
export const CREATE_SECURITY_TEST_FOR_REVIEW = 'CREATE_SECURITY_TEST_FOR_REVIEW';
export const GET_SECURITY_TESTS = 'GET_SECURITY_TESTS';
export const DELETE_SECURITY_TEST = 'DELETE_SECURITY_TEST';
export const COMPLETE_SECURITY_TEST = 'COMPLETE_SECURITY_TEST';
export const CLEAR_SECURITY_TEST_DETAILS = 'CLEAR_SECURITY_TEST_DETAILS';
export const GET_SECURITY_TEST_DETAILS = 'GET_SECURITY_TEST_DETAILS';

export const GET_THREAT_MODELS = 'GET_THREAT_MODELS';
export const CREATE_THREAT_MODEL = 'CREATE_THREAT_MODEL';
export const CREATE_THREAT_MODEL_FOR_REVIEW = 'CREATE_THREAT_MODEL_FOR_REVIEW';
export const DELETE_THREAT_MODEL = 'DELETE_THREAT_MODEL';
export const GET_THREAT_MODEL_DETAILS = 'GET_THREAT_MODEL_DETAILS';
export const CLEAR_THREAT_MODEL_DETAILS = 'CLEAR_THREAT_MODEL_DETAILS';
export const COMPLETE_THREAT_MODEL = 'COMPLETE_THREAT_MODEL';
