export const GET_SERVICES = 'GET_SERVICES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const LOADED_SERVICES = 'LOADED_SERVICES';

export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS'
export const CLEAR_SERVICE_DETAILS = 'CLEAR_SERVICE_DETAILS'
export const UPDATE_SERVICE_DETAILS = 'UPDATE_SERVICE_DETAILS'

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const LOADED_TEMPLATES = 'LOADED_TEMPLATES';

export const GET_TEMPLATE_DETAILS = 'GET_TEMPLATES_DETAILS';
export const UPDATE_TEMPLATE_DETAILS = 'UPDATE_TEMPLATES_DETAILS';
export const CLEAR_TEMPLATE_DETAILS = 'CLEAR_TEMPLATE_DETAILS';

export const GET_REQUIREMENTS = 'GET_REQUIREMENTS';

export const GET_EXERCISES = 'GET_EXERCISES';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const LOADED_EXERCISES = 'LOADED_EXERCISES';

export const GET_EXERCISE_DETAILS = 'GET_EXERCISE_DETAILS';
export const CLEAR_EXERCISE_DETAILS = 'CLEAR_EXERCISE_DETAILS';
export const FINISH_EXERCISE = 'FINISH_EXERCISE';

export const GET_TEST_CASE = 'GET_TEST_CASE'
export const CLEAR_TEST_CASES = 'CLEAR_TEST_CASES'
export const UPDATE_TEST_CASE = 'UPDATE_TEST_CASE'
export const BULK_UPDATE_TEST_CASE = 'BULK_UPDATE_TEST_CASE'

export const GET_FINDINGS = 'GET_FINDINGS'
export const CREATE_FINDING = 'CREATE_FINDING'
export const UPDATE_FINDING = 'UPDATE_FINDING'
export const CLEAR_FINDINGS = 'CLEAR_FINDINGS'
export const DELETE_FINDING = 'DELETE_FINDING'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOAD = 'USER_LOAD'
export const USER_LOADING = 'USER_LOADING'
